[package]
name = "complete-pic"
version = "0.1.0"
edition = "2021"
authors = ["akabinds <bindsdev@gmail.com>"]
repository = "https://github.com/akabinds/complete-pic"
homepage = "https://github.com/akabinds/complete-pic"
description = "A complete interface for the legacy 8259 PIC and the newer APIC."
readme = "README.md"
license = "MIT"
keywords = ["no_std", "kernel", "interrupts", "os", "osdev", "ia32", "x86", "x86-64", "amd64"]
exclude = ["./.github/*"]

[dependencies]

[features]
default = ["nightly", "apic"]

# Enable interface for the legacy 8259 PIC
8259pic = []

# Enable interface for the newer APIC. Enabled by default
apic = []

# Enable nightly for use of unstable features. Enabled by default
nightly = []
