name: CI

on:
  push:
    branches: [master]
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - uses: actions-rs/cargo@v1.0.1
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/cargo@v1.0.1
        with:
          command: clippy
        env:
          RUSTFLAGS: -Dwarnings

  build:
    needs: checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1.0.1
        with:
          command: build
          args: --all-features
      - uses: actions-rs/cargo@v1.0.1
        with:
          command: doc  
        env:
          RUSTDOCFLAGS: -Dwarnings    